### ISSUE TITLE
Deactivate VSCode organize import

### ISSUE THREAD

**Issue by gcoutable** [eclipse/sirius-components#46]
## Details

* [x] Can you reproduce the problem all the time?
* [x] Are you running the latest version?
* [x] Did you check the documentation?
* [x] Are you reporting this issue to the correct repository?
* [x] Did you perform a search to check if the issue does not exist already?

## Current behavior

Vs code change the imports organization when a file is saved.

## Expected behavior

Don't touch anything

## Steps to reproduce

Save a file with organize import activated in user settings

## Environment

Sirius Components version: 0.1.0

Browser in which the issue has been reproduced:

* [ ] Chrome (desktop) version XX
* [ ] Chrome (Android) version XX
* [ ] Chrome (iOS) version XX
* [ ] Firefox version XX
* [ ] Safari (desktop) version XX
* [ ] Safari (iOS) version XX
* [ ] IE version XX
* [ ] Edge version XX
 
For Tooling issues:

* Yarn version: 1.6
* Node version: XX
* Platform: VSCode 1.23.1

Others:

**Comment by sbegaudeau** [comment]
Closing this issue since the pull request has been merged.
